  <?php echo $this->flashSession->output(); 
 
  $username='';
  $password='';
  $rememberMe='';
 
  if($this->cookies->has("username") && $this->cookies->has("password") )
  {
      $username=$this->cookies->get("username");
      $password=$this->cookies->get("password");
      $rememberMe='checked';
  }
?>
<!DOCTYPE html>
<html lang="en">
<head>
 <!-- Standard Meta -->
 <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>Bootstrap 4 Login Form</title>

    <!-- Stylesheets -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="<?php echo $this->url->getBaseUri().'/public/css/ihatethiswork.css' ?>" rel="stylesheet">
</head>

<!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->
<body>
   
<body>
        <div class="container">
        <form class="form-horizontal" role="form" method="POST" action="">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <h2>Please Login</h2>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="form-group has-danger">
                        <label class="sr-only" for="email">E-Mail Address</label>
                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                            <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-at"></i></div>
                            <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Enter email" required autofocus value="<?php if(isset($username))echo $username; ?>">

                        </div>
                    </div>
                </div>
               
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="sr-only" for="password">Password</label>
                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                            <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                            <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required value="<?php if(isset($password))echo $password; ?>">

                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                        <!-- Put password error message here -->    
                        </span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6" style="padding-top: .35rem">
                <div id="remember" class="checkbox">
                    <label>
                    <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>> Remember me
                    </label>
                </div>
                </div>
            </div>
            <div class="row" style="padding-top: 1rem">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-success"><i class="fa fa-sign-in"></i> Login</button>
                </div>
            </div>
        </form>
    </div>
</body>
</body>

<!-- <form action="" method="post">
  
    <div class="form-group">
      <label>Email address</label>
      <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
    </div>
    <div class="form-group">
      <label>Password</label>
      <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
     
    </div>
    <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>>
 
      <label class="form-check-label" for="rememberMe">Remember me</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
   
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
   
  </form> -->

  
